import type { Metadata } from "next"
import Link from "next/link"
import { SCREENING_ENGINE_VERSION } from "@/lib/screening/version"

// The public landing surface is fully static: crawlers, link previews, and
// non-JS clients must receive the complete marketing copy, the decision-support
// disclaimer, and a working demo entry point without hydration.
export const dynamic = "force-static"

export const metadata: Metadata = {
  alternates: {
    canonical: "/",
  },
}

const softwareApplicationJsonLd = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  name: "OpenRx",
  applicationCategory: "MedicalApplication",
  operatingSystem: "Web",
  url: "https://openrx.health",
  description:
    "Ask a clinical question in plain English. OpenRx provides source-linked, version-stamped answers from a deterministic guideline engine and a sandboxed path from denial to appeal preparation.",
  offers: {
    "@type": "Offer",
    price: "0",
    priceCurrency: "USD",
    description: "Free guideline-based screening preview",
  },
}

const HOW_IT_WORKS = [
  {
    step: "01",
    title: "Ask in plain English",
    body: "Type a clinical question the way you would say it — “age 45 male, what screening is due?” No forms, no portal maze.",
  },
  {
    step: "02",
    title: "A deterministic engine answers",
    body: "Screening guidance comes from encoded USPSTF rules, not model improvisation. Every recommendation carries its source, evidence grade, guideline version, and engine version.",
  },
  {
    step: "03",
    title: "Denial to appeal, sandboxed",
    body: "Bring a prior-authorization denial and walk a synthetic case from evidence retrieval to a clinician-reviewable appeal draft, with a simulated FHIR trace and an audit row for every step.",
  },
  {
    step: "04",
    title: "Referrals only with consent",
    body: "Choose a verified provider and approve exactly the fields you share — every disclosure is consent-scoped, hashed, and audit-logged, and notifications carry only a neutral link.",
  },
]

export default function HomePage() {
  return (
    <main id="main-content" className="relative mx-auto w-full max-w-[1100px] px-5 pb-20 pt-10 sm:px-8 sm:pt-16">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(softwareApplicationJsonLd) }}
      />

      {/* Hero */}
      <section aria-labelledby="hero-heading" className="route-stack">
        <p className="font-mono text-[11px] uppercase tracking-[0.22em] text-accent">
          Decision support · source-linked · auditable
        </p>
        <h1
          id="hero-heading"
          className="max-w-[16ch] font-serif text-[clamp(2.4rem,6vw,4.2rem)] font-medium leading-[1.04] tracking-[-0.015em] text-primary text-balance"
        >
          Ask a clinical question. Get an answer you can audit.
        </h1>
        <p className="max-w-[58ch] text-[15.5px] leading-relaxed text-secondary">
          OpenRx answers in plain English and shows its work: every screening recommendation is
          generated by a deterministic guideline engine and stamped with its source, evidence grade,
          and guideline version — then carries you from a coverage denial to a prepared appeal in a
          clearly labeled sandbox.
        </p>
        <div className="flex flex-wrap items-center gap-3 pt-1">
          <Link
            href="/chat"
            className="inline-flex items-center gap-2 rounded-full bg-accent px-6 py-3 text-[13.5px] font-semibold text-black transition hover:bg-accent-light"
          >
            Ask a clinical question
          </Link>
          <Link
            href="/demo"
            className="inline-flex items-center gap-2 rounded-full border border-border-strong px-6 py-3 text-[13.5px] font-semibold text-primary transition hover:border-accent hover:text-accent"
          >
            See the denial-to-appeal demo
          </Link>
        </div>
      </section>

      {/* Specimen: a real version-stamped recommendation, rendered statically */}
      <section aria-label="Example of a version-stamped recommendation" className="mt-14">
        <div className="surface-hero overflow-hidden">
          <div className="flex items-center justify-between border-b border-border px-5 py-3">
            <span className="section-title">What an auditable answer looks like</span>
            <span className="font-mono text-[10.5px] text-subtle">specimen · synthetic input</span>
          </div>
          <div className="grid gap-0 sm:grid-cols-[1fr_1.4fr]">
            <div className="border-b border-border px-5 py-5 sm:border-b-0 sm:border-r">
              <p className="font-mono text-[11px] uppercase tracking-[0.14em] text-subtle">Patient asks</p>
              <p className="mt-3 font-serif text-[22px] leading-snug text-primary">
                &ldquo;age 45 male — what screening is due?&rdquo;
              </p>
            </div>
            <div className="px-5 py-5">
              <p className="font-mono text-[11px] uppercase tracking-[0.14em] text-subtle">Engine answers</p>
              <p className="mt-3 text-[15px] font-medium text-primary">
                Colorectal cancer screening — <span className="text-accent">due</span>
              </p>
              <p className="mt-1.5 max-w-[52ch] text-[13.5px] leading-relaxed text-muted">
                USPSTF recommends colorectal cancer screening for average-risk adults ages 45 to 75.
              </p>
              <dl className="mt-4 grid grid-cols-2 gap-x-6 gap-y-2 font-mono text-[11px] leading-relaxed sm:grid-cols-3">
                <div>
                  <dt className="text-subtle">Source</dt>
                  <dd className="text-secondary">USPSTF · 2021-05-18</dd>
                </div>
                <div>
                  <dt className="text-subtle">Evidence grade</dt>
                  <dd className="text-secondary">B</dd>
                </div>
                <div className="col-span-2 sm:col-span-1">
                  <dt className="text-subtle">Engine version</dt>
                  <dd className="text-secondary">{SCREENING_ENGINE_VERSION}</dd>
                </div>
              </dl>
            </div>
          </div>
        </div>
      </section>

      {/* How it works */}
      <section aria-labelledby="how-heading" className="mt-16">
        <h2 id="how-heading" className="section-title">
          How OpenRx works
        </h2>
        <ol className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          {HOW_IT_WORKS.map((item) => (
            <li key={item.step} className="surface-card p-5">
              <span className="font-mono text-[11px] text-accent">{item.step}</span>
              <h3 className="mt-3 font-serif text-[19px] font-medium leading-snug text-primary">{item.title}</h3>
              <p className="mt-2 text-[13.5px] leading-relaxed text-muted">{item.body}</p>
            </li>
          ))}
        </ol>
      </section>

      {/* Decision-support disclaimer */}
      <section aria-labelledby="disclaimer-heading" className="mt-16">
        <div className="surface-muted px-5 py-5">
          <h2 id="disclaimer-heading" className="section-title">
            What OpenRx is — and is not
          </h2>
          <p className="mt-3 max-w-[72ch] text-[13.5px] leading-relaxed text-secondary">
            OpenRx is clinical decision support and care navigation, not a diagnosis, medical order,
            prescription, or insurance approval, and not a substitute for clinician judgment. The
            denial-to-appeal workflow runs on synthetic cases in a sandbox: an authorized clinician
            must review medical necessity, current guideline access, and payer criteria before any
            real submission. If you have emergency symptoms, call 911 or seek emergency care now.
          </p>
        </div>
      </section>

      {/* Footer links */}
      <footer className="mt-16 flex flex-wrap items-center gap-x-6 gap-y-2 border-t border-border pt-6 text-[12.5px] text-muted">
        <Link href="/chat" className="transition hover:text-accent">Open the chat</Link>
        <Link href="/demo" className="transition hover:text-accent">Denial-to-appeal demo</Link>
        <Link href="/trust" className="transition hover:text-accent">Trust &amp; safety</Link>
        <Link href="/privacy-explained" className="transition hover:text-accent">Privacy, explained</Link>
        <span className="ml-auto font-mono text-[10.5px] text-subtle">openrx.health</span>
      </footer>
    </main>
  )
}
