export const openRxDesignTokens = {
  meta: {
    name: "OpenRx clinical infrastructure",
    version: "2026.06.12",
    status: "foundation",
    intent:
      "Clinical-grade trust for patient navigation, with precise developer credibility for prior-auth and MCP workflows.",
  },

  color: {
    primitive: {
      ink: {
        950: "#06111D",
        900: "#0A1C2E",
        800: "#12314D",
        700: "#1B496D",
        600: "#256284",
      },
      clinicalBlue: {
        700: "#174EA6",
        600: "#1D5FD1",
        500: "#2D7FF9",
        100: "#D9E9FF",
        50: "#EEF6FF",
      },
      careTeal: {
        700: "#0F6B66",
        600: "#12817B",
        500: "#18A7A0",
        100: "#D8F3F0",
        50: "#EFFBFA",
      },
      sage: {
        700: "#2F665D",
        600: "#3B7A70",
        500: "#57988B",
        100: "#E0F0EC",
        50: "#F2FAF7",
      },
      amber: {
        700: "#8A4B00",
        600: "#A45C00",
        500: "#C77600",
        100: "#FFE8B8",
        50: "#FFF7E6",
      },
      red: {
        700: "#9F1C14",
        600: "#B42318",
        500: "#D92D20",
        100: "#FEE4E2",
        50: "#FFF2F1",
      },
      neutral: {
        0: "#FFFFFF",
        25: "#FCFCFA",
        50: "#F7F8F4",
        100: "#ECEFE8",
        200: "#DDE3DA",
        300: "#C4CEC0",
        500: "#5F6B63",
        700: "#35443C",
        900: "#111B17",
      },
    },

    semantic: {
      patientLight: {
        background: "#F7F8F4",
        backgroundRaised: "#FFFFFF",
        surface: "#FFFFFF",
        surfaceMuted: "#F2FAF7",
        surfaceAccent: "#EEF6FF",
        textPrimary: "#06111D",
        textSecondary: "#35443C",
        textMuted: "#5F6B63",
        border: "#DDE3DA",
        borderStrong: "#C4CEC0",
        action: "#174EA6",
        actionHover: "#0A1C2E",
        actionText: "#FFFFFF",
        trust: "#0F6B66",
        warning: "#8A4B00",
        danger: "#B42318",
        focusRing: "rgba(29, 95, 209, 0.28)",
      },
      developerDark: {
        background: "#06111D",
        backgroundRaised: "#0A1C2E",
        surface: "#0E253A",
        surfaceMuted: "#12314D",
        surfaceAccent: "#0B3A44",
        textPrimary: "#F7F8F4",
        textSecondary: "#DDE3DA",
        textMuted: "#9FAEA5",
        border: "rgba(221, 227, 218, 0.14)",
        borderStrong: "rgba(221, 227, 218, 0.26)",
        action: "#18A7A0",
        actionHover: "#D8F3F0",
        actionText: "#06111D",
        trust: "#57988B",
        warning: "#FFE8B8",
        danger: "#FEE4E2",
        focusRing: "rgba(24, 167, 160, 0.34)",
      },
    },
  },

  typography: {
    fontFamily: {
      patient:
        'var(--font-sans), ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      display:
        'var(--font-sans), ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      developer:
        'var(--font-sans), ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      mono:
        '"IBM Plex Mono", "SFMono-Regular", Consolas, "Liberation Mono", monospace',
    },
    weight: {
      regular: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
    },
    tracking: {
      body: "0",
      label: "0.01em",
      eyebrow: "0.08em",
    },
    scale: {
      caption: { fontSize: "0.75rem", lineHeight: "1rem" },
      label: { fontSize: "0.8125rem", lineHeight: "1.125rem" },
      bodySm: { fontSize: "0.875rem", lineHeight: "1.375rem" },
      body: { fontSize: "1rem", lineHeight: "1.625rem" },
      bodyLg: { fontSize: "1.125rem", lineHeight: "1.75rem" },
      titleSm: { fontSize: "1.25rem", lineHeight: "1.625rem" },
      title: { fontSize: "1.5rem", lineHeight: "1.875rem" },
      titleLg: { fontSize: "2rem", lineHeight: "2.375rem" },
      displaySm: { fontSize: "clamp(2rem, 6vw, 3rem)", lineHeight: "1.08" },
      display: { fontSize: "clamp(2.5rem, 7vw, 4.75rem)", lineHeight: "1.02" },
    },
  },

  spacing: {
    0: "0",
    1: "0.25rem",
    2: "0.5rem",
    3: "0.75rem",
    4: "1rem",
    5: "1.25rem",
    6: "1.5rem",
    8: "2rem",
    10: "2.5rem",
    12: "3rem",
    16: "4rem",
    20: "5rem",
    24: "6rem",
    layout: {
      pageX: "clamp(1rem, 4vw, 3.5rem)",
      sectionY: "clamp(3rem, 8vw, 7rem)",
      cardGap: "1rem",
      shellMax: "72rem",
      readingMeasure: "42rem",
    },
  },

  radius: {
    none: "0",
    xs: "0.25rem",
    sm: "0.375rem",
    md: "0.5rem",
    lg: "0.75rem",
    xl: "1rem",
    pill: "999px",
    component: {
      button: "0.5rem",
      card: "0.5rem",
      panel: "0.75rem",
      input: "0.5rem",
      modal: "1rem",
    },
  },

  shadow: {
    none: "none",
    hairline: "0 1px 0 rgba(6, 17, 29, 0.08)",
    card: "0 1px 2px rgba(6, 17, 29, 0.06), 0 8px 24px rgba(6, 17, 29, 0.06)",
    elevated: "0 16px 44px rgba(6, 17, 29, 0.12)",
    developerPanel: "0 18px 60px rgba(0, 0, 0, 0.36)",
    focus: "0 0 0 3px var(--orx-focus-ring)",
  },

  motion: {
    duration: {
      fast: "120ms",
      base: "180ms",
      slow: "260ms",
    },
    easing: {
      standard: "cubic-bezier(0.2, 0, 0, 1)",
      enter: "cubic-bezier(0, 0, 0.2, 1)",
      exit: "cubic-bezier(0.4, 0, 1, 1)",
    },
  },

  component: {
    button: {
      base: {
        borderRadius: "0.5rem",
        fontWeight: 700,
        minHeight: "2.75rem",
        paddingInline: "1rem",
        transition: "background-color 180ms ease, border-color 180ms ease, transform 120ms ease",
      },
      size: {
        sm: { minHeight: "2.25rem", paddingInline: "0.75rem", fontSize: "0.875rem" },
        md: { minHeight: "2.75rem", paddingInline: "1rem", fontSize: "0.9375rem" },
        lg: { minHeight: "3.25rem", paddingInline: "1.25rem", fontSize: "1rem" },
      },
      variant: {
        patientPrimary: {
          background: "var(--orx-action)",
          color: "var(--orx-action-text)",
          borderColor: "var(--orx-action)",
        },
        patientSecondary: {
          background: "var(--orx-surface)",
          color: "var(--orx-text-primary)",
          borderColor: "var(--orx-border-strong)",
        },
        developerPrimary: {
          background: "var(--orx-action)",
          color: "var(--orx-action-text)",
          borderColor: "var(--orx-action)",
        },
        ghost: {
          background: "transparent",
          color: "var(--orx-text-secondary)",
          borderColor: "transparent",
        },
        danger: {
          background: "var(--orx-danger)",
          color: "#FFFFFF",
          borderColor: "var(--orx-danger)",
        },
      },
    },
    card: {
      default: {
        background: "var(--orx-surface)",
        borderColor: "var(--orx-border)",
        borderRadius: "0.5rem",
        boxShadow: "var(--orx-shadow-card)",
      },
      recommendation: {
        background: "var(--orx-surface)",
        borderColor: "var(--orx-border-strong)",
        borderLeftColor: "var(--orx-trust)",
        borderRadius: "0.5rem",
      },
      developerPanel: {
        background: "var(--orx-surface)",
        borderColor: "var(--orx-border)",
        borderRadius: "0.75rem",
        boxShadow: "var(--orx-shadow-developer-panel)",
      },
      compliance: {
        background: "var(--orx-surface-muted)",
        borderColor: "var(--orx-border)",
        borderRadius: "0.5rem",
      },
    },
    form: {
      input: {
        background: "var(--orx-surface)",
        color: "var(--orx-text-primary)",
        borderColor: "var(--orx-border-strong)",
        borderRadius: "0.5rem",
        minHeight: "2.75rem",
      },
      textarea: {
        background: "var(--orx-surface)",
        color: "var(--orx-text-primary)",
        borderColor: "var(--orx-border-strong)",
        borderRadius: "0.75rem",
        minHeight: "8rem",
      },
      label: {
        color: "var(--orx-text-secondary)",
        fontSize: "0.8125rem",
        fontWeight: 700,
      },
      helpText: {
        color: "var(--orx-text-muted)",
        fontSize: "0.875rem",
      },
    },
    badge: {
      source: {
        background: "var(--orx-surface-accent)",
        color: "var(--orx-action)",
        borderColor: "var(--orx-border)",
      },
      grade: {
        background: "var(--orx-surface-muted)",
        color: "var(--orx-trust)",
        borderColor: "var(--orx-border)",
      },
      due: {
        background: "var(--orx-warning-muted)",
        color: "var(--orx-warning)",
        borderColor: "var(--orx-warning-border)",
      },
      verified: {
        background: "var(--orx-trust-muted)",
        color: "var(--orx-trust)",
        borderColor: "var(--orx-trust-border)",
      },
    },
  },
} as const

export const openRxCssVariableThemes = {
  patientLight: {
    "--orx-background": openRxDesignTokens.color.semantic.patientLight.background,
    "--orx-background-raised": openRxDesignTokens.color.semantic.patientLight.backgroundRaised,
    "--orx-surface": openRxDesignTokens.color.semantic.patientLight.surface,
    "--orx-surface-muted": openRxDesignTokens.color.semantic.patientLight.surfaceMuted,
    "--orx-surface-accent": openRxDesignTokens.color.semantic.patientLight.surfaceAccent,
    "--orx-text-primary": openRxDesignTokens.color.semantic.patientLight.textPrimary,
    "--orx-text-secondary": openRxDesignTokens.color.semantic.patientLight.textSecondary,
    "--orx-text-muted": openRxDesignTokens.color.semantic.patientLight.textMuted,
    "--orx-border": openRxDesignTokens.color.semantic.patientLight.border,
    "--orx-border-strong": openRxDesignTokens.color.semantic.patientLight.borderStrong,
    "--orx-action": openRxDesignTokens.color.semantic.patientLight.action,
    "--orx-action-hover": openRxDesignTokens.color.semantic.patientLight.actionHover,
    "--orx-action-text": openRxDesignTokens.color.semantic.patientLight.actionText,
    "--orx-trust": openRxDesignTokens.color.semantic.patientLight.trust,
    "--orx-warning": openRxDesignTokens.color.semantic.patientLight.warning,
    "--orx-danger": openRxDesignTokens.color.semantic.patientLight.danger,
    "--orx-focus-ring": openRxDesignTokens.color.semantic.patientLight.focusRing,
    "--orx-trust-muted": openRxDesignTokens.color.primitive.sage[50],
    "--orx-trust-border": openRxDesignTokens.color.primitive.sage[100],
    "--orx-warning-muted": openRxDesignTokens.color.primitive.amber[50],
    "--orx-warning-border": openRxDesignTokens.color.primitive.amber[100],
    "--orx-shadow-card": openRxDesignTokens.shadow.card,
    "--orx-shadow-developer-panel": openRxDesignTokens.shadow.developerPanel,
    "--orx-shadow-focus": openRxDesignTokens.shadow.focus,
  },
  developerDark: {
    "--orx-background": openRxDesignTokens.color.semantic.developerDark.background,
    "--orx-background-raised": openRxDesignTokens.color.semantic.developerDark.backgroundRaised,
    "--orx-surface": openRxDesignTokens.color.semantic.developerDark.surface,
    "--orx-surface-muted": openRxDesignTokens.color.semantic.developerDark.surfaceMuted,
    "--orx-surface-accent": openRxDesignTokens.color.semantic.developerDark.surfaceAccent,
    "--orx-text-primary": openRxDesignTokens.color.semantic.developerDark.textPrimary,
    "--orx-text-secondary": openRxDesignTokens.color.semantic.developerDark.textSecondary,
    "--orx-text-muted": openRxDesignTokens.color.semantic.developerDark.textMuted,
    "--orx-border": openRxDesignTokens.color.semantic.developerDark.border,
    "--orx-border-strong": openRxDesignTokens.color.semantic.developerDark.borderStrong,
    "--orx-action": openRxDesignTokens.color.semantic.developerDark.action,
    "--orx-action-hover": openRxDesignTokens.color.semantic.developerDark.actionHover,
    "--orx-action-text": openRxDesignTokens.color.semantic.developerDark.actionText,
    "--orx-trust": openRxDesignTokens.color.semantic.developerDark.trust,
    "--orx-warning": openRxDesignTokens.color.semantic.developerDark.warning,
    "--orx-danger": openRxDesignTokens.color.semantic.developerDark.danger,
    "--orx-focus-ring": openRxDesignTokens.color.semantic.developerDark.focusRing,
    "--orx-trust-muted": "rgba(87, 152, 139, 0.18)",
    "--orx-trust-border": "rgba(87, 152, 139, 0.38)",
    "--orx-warning-muted": "rgba(255, 232, 184, 0.12)",
    "--orx-warning-border": "rgba(255, 232, 184, 0.30)",
    "--orx-shadow-card": "0 1px 2px rgba(0, 0, 0, 0.24)",
    "--orx-shadow-developer-panel": openRxDesignTokens.shadow.developerPanel,
    "--orx-shadow-focus": openRxDesignTokens.shadow.focus,
  },
} as const

export type OpenRxDesignTokens = typeof openRxDesignTokens
export type OpenRxThemeName = keyof typeof openRxCssVariableThemes
